{% set name = "pandas-indexing" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2f8a18f82e58c02d04038a5af680d7447bfb8deae1e163725bd8ad37655237dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools >=46.1.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8,<4.0
    - pandas >=1.2
    - deprecated
    - attrs

test:
  imports:
    - pandas_indexing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coroa/pandas-indexing
  summary: Helpers to facilitate working with pandas indices in particular multiindices
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    pandas-indexing is a helpers package to make interacting with pandas multi-indices less painful.
    It contains functions, that
    - filter easily into multi indices: isin, ismatch
    - add or update levels in a multiindex: assignlevel
    - select one or multiple specific levels: projectlevel
  doc_url: https://pandas-indexing.readthedocs.io/
  dev_url: https://github.com/coroa/pandas-indexing

extra:
  recipe-maintainers:
    - coroa
